DROP TABLE IF EXISTS `ipayment_log`;
CREATE TABLE IF NOT EXISTS `ipayment_log` (
  `ipayment_log_id` int(11) NOT NULL AUTO_INCREMENT,
  `orders_id` int(11) NOT NULL,
  `action` varchar(255) NOT NULL,
  `trxuser_id` varchar(255) NOT NULL,
  `trx_currency` varchar(255) NOT NULL,
  `trx_amount` varchar(255) NOT NULL,
  `trx_typ` varchar(255) NOT NULL,
  `addr_name` varchar(255) NOT NULL,
  `addr_email` varchar(255) NOT NULL,
  `shopper_id` varchar(255) NOT NULL,
  `client_name` varchar(255) NOT NULL,
  `client_version` varchar(255) NOT NULL,
  `addr_street` varchar(255) NOT NULL,
  `addr_zip` varchar(255) NOT NULL,
  `addr_city` varchar(255) NOT NULL,
  `trx_paymenttyp` varchar(255) NOT NULL,
  `ret_transdate` varchar(255) NOT NULL,
  `ret_transtime` varchar(255) NOT NULL,
  `ret_errorcode` varchar(255) NOT NULL,
  `ret_fatalerror` varchar(255) NOT NULL,
  `ret_errormsg` varchar(255) NOT NULL,
  `ret_additionalmsg` varchar(255) NOT NULL,
  `ret_authcode` varchar(255) NOT NULL,
  `ret_ip` varchar(255) NOT NULL,
  `ret_booknr` varchar(255) NOT NULL,
  `ret_trx_number` varchar(255) NOT NULL,
  `ret_param_checksum` varchar(255) NOT NULL,
  `redirect_needed` varchar(255) NOT NULL,
  `trx_paymentmethod` varchar(255) NOT NULL,
  `trx_paymentdata_country` varchar(255) NOT NULL,
  `trx_remoteip_country` varchar(255) NOT NULL,
  `ret_status` varchar(255) NOT NULL,
  `trx_payauth_status` varchar(255) NOT NULL,
  `trx_issuer_avs_response` varchar(255) NOT NULL,
  `ret_url_checksum` varchar(255) NOT NULL,
  `addr_check_result` varchar(255) NOT NULL,
  `paydata` varchar(255) NOT NULL,
  PRIMARY KEY (`ipayment_log_id`),
  KEY `orders_id` (`orders_id`)
) ENGINE=MyISAM;