DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
  `orders_id` int(11) NOT NULL auto_increment,
  `customers_id` int(11) NOT NULL default '0',
  `customers_cid` varchar(32) default NULL,
  `customers_vat_id` varchar(20) default NULL,
  `customers_status` int(11) default NULL,
  `customers_status_name` varchar(32) NOT NULL default '',
  `customers_status_image` varchar(64) default NULL,
  `customers_status_discount` decimal(4,2) default NULL,
  `customers_name` varchar(64) NOT NULL default '',
  `customers_firstname` varchar(64) NOT NULL default '',
  `customers_lastname` varchar(64) NOT NULL default '',
  `customers_gender` char(1) NOT NULL default '',
  `customers_company` varchar(255) default NULL,
  `customers_street_address` varchar(64) NOT NULL default '',
  `customers_suburb` varchar(32) default NULL,
  `customers_city` varchar(32) NOT NULL default '',
  `customers_postcode` varchar(10) NOT NULL default '',
  `customers_state` varchar(32) default NULL,
  `customers_country` varchar(32) NOT NULL default '',
  `customers_telephone` varchar(32) NOT NULL default '',
  `customers_email_address` varchar(96) NOT NULL default '',
  `customers_address_format_id` int(5) NOT NULL default '0',
  `delivery_name` varchar(64) NOT NULL default '',
  `delivery_firstname` varchar(64) NOT NULL default '',
  `delivery_lastname` varchar(64) NOT NULL default '',
  `delivery_gender` char(1) NOT NULL default '',
  `delivery_company` varchar(255) default NULL,
  `delivery_street_address` varchar(64) NOT NULL default '',
  `delivery_suburb` varchar(32) default NULL,
  `delivery_city` varchar(32) NOT NULL default '',
  `delivery_postcode` varchar(10) NOT NULL default '',
  `delivery_state` varchar(32) default NULL,
  `delivery_country` varchar(32) NOT NULL default '',
  `delivery_country_iso_code_2` char(2) NOT NULL default '',
  `delivery_address_format_id` int(5) NOT NULL default '0',
  `billing_name` varchar(64) NOT NULL default '',
  `billing_firstname` varchar(64) NOT NULL default '',
  `billing_lastname` varchar(64) NOT NULL default '',
  `billing_gender` char(1) NOT NULL default '',
  `billing_company` varchar(255) default NULL,
  `billing_street_address` varchar(64) NOT NULL default '',
  `billing_suburb` varchar(32) default NULL,
  `billing_city` varchar(32) NOT NULL default '',
  `billing_postcode` varchar(10) NOT NULL default '',
  `billing_state` varchar(32) default NULL,
  `billing_country` varchar(32) NOT NULL default '',
  `billing_country_iso_code_2` char(2) NOT NULL default '',
  `billing_address_format_id` int(5) NOT NULL default '0',
  `payment_method` varchar(32) NOT NULL default '',
  `cc_type` varchar(20) default NULL,
  `cc_owner` varchar(64) default NULL,
  `cc_number` varchar(64) default NULL,
  `cc_expires` varchar(4) default NULL,
  `cc_start` varchar(4) default NULL,
  `cc_issue` char(3) default NULL,
  `cc_cvv` varchar(4) default NULL,
  `comments` text default NULL,
  `last_modified` datetime default NULL,
  `date_purchased` datetime default NULL,
  `orders_status` int(5) NOT NULL default '0',
  `orders_date_finished` datetime default NULL,
  `currency` char(3) default NULL,
  `currency_value` decimal(14,6) default NULL,
  `account_type` int(1) NOT NULL default '0',
  `payment_class` varchar(32) NOT NULL default '',
  `shipping_method` varchar(32) NOT NULL default '',
  `shipping_class` varchar(32) NOT NULL default '',
  `customers_ip` varchar(32) NOT NULL default '',
  `language` varchar(32) NOT NULL default '',
  `afterbuy_success` int(1) NOT NULL default '0',
  `afterbuy_id` int(32) NOT NULL default '0',
  `refferers_id` varchar(32) NOT NULL default '',
  `conversion_type` int(1) NOT NULL default '0',
  `orders_ident_key` varchar(128) default NULL,
  `gm_orders_id` int(11) default NULL,
  `gm_packings_id` int(11) default NULL,
  `gm_orders_code` varchar(255) NOT NULL,
  `gm_packings_code` varchar(255) NOT NULL,
  `gm_order_html` MEDIUMTEXT,
  `gm_order_txt` MEDIUMTEXT NOT NULL,
  `gm_order_send_date` datetime NOT NULL,
  `gm_send_order_status` int(1) NOT NULL,
  `gm_cancel_date` datetime NOT NULL,
  `abandonment_download` tinyint(1) NOT NULL,
  `abandonment_service` tinyint(1) NOT NULL,
  `orders_hash` varchar(32) NOT NULL,
  `intraship_shipmentnumber` varchar(255) NOT NULL,
  `exported` TINYINT NOT NULL DEFAULT '0' COMMENT 'already exported to WaWi?',
  INDEX (`orders_status`),
  PRIMARY KEY  (`orders_id`),
  KEY `date_purchased` (`date_purchased`)
) ENGINE=MyISAM AUTO_INCREMENT=400210;